# Generated by Django 5.1.6 on 2025-03-05 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cabineterria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cabinet',
            new_name='CabinetModel',
        ),
    ]
