# Generated by Django 5.1.6 on 2025-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cabineterria', '0004_usercabinetstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetmodel',
            name='requires_questions_remember',
            field=models.BooleanField(default=False),
        ),
    ]
